implement part_03
the-action-man/tn-js pull request #1
Opened 2020-05-29 00:23 UTC by the-action-man

2020-05-29 15:49 UTC, arswarog requested changes

2020-05-29 15:49 UTC, arswarog commented on part_03_deepening_into_js/01/03_01.js
> +    }
проще выполнить это используюя методы массива filter и reduce
это будет короче и читабельнее

2020-05-29 15:49 UTC, arswarog commented on part_03_deepening_into_js/02/03_02.js
> +    }
здесь цикл выполняет задачи метода map.
Исправьте на map

2020-05-29 15:49 UTC, arswarog commented on part_03_deepening_into_js/02/03_02.js
> +}
требуется выполнить при помощи метода reduce
это немного короче и зачастую воспринимается проще

2020-05-29 15:49 UTC, arswarog commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +        countOfSeats: (flight.seats + flight.businessSeats),
скобки не обязательны

2020-05-29 15:49 UTC, arswarog commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +            registeredSeats++;
здесь цикл выполняет задачи метода filter.
Исправьте на filter

2020-05-30 11:13 UTC, the-action-man commented on part_03_deepening_into_js/01/03_01.js
> +    }
понял
спасибо

2020-05-30 11:46 UTC, the-action-man commented on part_03_deepening_into_js/02/03_02.js
> +    }
сделал 
спасибо!

2020-05-30 11:46 UTC, the-action-man commented on part_03_deepening_into_js/02/03_02.js
> +}
Сделано
Спасибо!

2020-05-30 12:03 UTC, the-action-man commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +            registeredSeats++;
сделано

2020-05-30 12:03 UTC, the-action-man commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +        countOfSeats: (flight.seats + flight.businessSeats),
ок

2020-05-31 09:29 UTC, arswarog approved these changes

2020-06-01 08:02 UTC, merged