Part 04 testing
the-action-man/tn-js pull request #2
Opened 2020-06-03 10:57 UTC by the-action-man

2020-06-04 10:50 UTC, index01d requested changes

2020-06-04 10:50 UTC, index01d commented on part_04_testing/01/04_01.js
> +    let sum = 0;
от промежуточной переменной можно избавиться, если использовать второй аргумент функции `reduce`.

```
const reducer = (accumulator, currentValue) => accumulator + currentValue;

// 1 + 2 + 3 + 4
console.log(array1.reduce(reducer));
// результат: 10

// 5 + 1 + 2 + 3 + 4
console.log(array1.reduce(reducer, 5));
// результат: 15
```

2020-06-04 10:50 UTC, index01d commented on part_04_testing/01/04_01.js
> +    if (count > 0) {
условие выглядит избыточным. Даже если положительных чисел не будет, то positiveNumbers будет содержать пустой массив и сумма получится 0. Избыточные условия сэкономят выполняемые инструкции, но усложнят чтение кода. В данном случае экономия несопоставима с усложнением.

2020-06-04 10:50 UTC, index01d commented on part_04_testing/01/04_01.test.js
> +describe('sumOfPositive', () => {
Не совсем семантичные названия сложны в понимании и поддержке. Хотелось бы, чтобы комплекты тестов назывались понятно и названия самих тестов однозначно определяли ожидаемое поведение.

Например "Десятичные дроби корректно суммируются" заместо "positive test #2"

2020-06-04 10:50 UTC, index01d commented on part_04_testing/02/04_02.js
> +        return [
Возможно, логичнее было бы вернуть ошибку для некорректных значений input (undefined, null). В любом случае, по заданию  не требуется обрабатывать некорректные значения входящего аргумента.

2020-06-04 10:50 UTC, index01d commented on part_04_testing/02/04_02.js
> +function defineObject(word) {
Стилистическое замечание: название defineObject неточно определяет назначение функции. Можно было бы выделить функцию `sumOfCharCodes`, которая возвращала бы сумму кодов символов, а итоговый объект сформировать в главной функции `wordStat`

2020-06-04 10:50 UTC, index01d commented on part_04_testing/02/04_02.js
> +    const chars_codes = chars.map(function(item) {
стилистическое замечание: часть объектов в листинге именуется camelCase'ом, а часть snake_case'ом. Хорошим тоном является именование переменных и функций в рамках проекта в едином стиле (рекомендуется camelCase). Подробнее 
https://ru.wikipedia.org/wiki/Snake_case
https://ru.wikipedia.org/wiki/CamelCase

2020-06-04 10:50 UTC, index01d commented on part_04_testing/02/04_02.js
> +        if (item === "")
Более функционально-ориентированным подходом было бы заранее очистить строку от повторяющихся пробелов. В данном случае `defineObject` получает заведомо слово до ближайшего пробела, так что это условие выглядит избыточным.

2020-06-04 20:38 UTC, the-action-man commented on part_04_testing/01/04_01.js
> +    let sum = 0;
понял.
Спасибо!

2020-06-04 20:41 UTC, the-action-man commented on part_04_testing/01/04_01.js
> +    if (count > 0) {
Спасибо!

2020-06-04 20:45 UTC, the-action-man commented on part_04_testing/01/04_01.test.js
> +describe('sumOfPositive', () => {
сделано
Спасибо!

2020-06-04 20:49 UTC, the-action-man commented on part_04_testing/02/04_02.js
> +        return [
В задании написано
```
минимум два теста на некорректных данных (если таковые могут быть) 
```

2020-06-05 08:19 UTC, the-action-man commented on part_04_testing/02/04_02.js
> +function defineObject(word) {
sumOfCharCodes is renamed to calcSumOfWordCharsCodes

2020-06-05 08:20 UTC, the-action-man commented on part_04_testing/02/04_02.js
> +    const chars_codes = chars.map(function(item) {
Да, спасибо! змеиный стиль - привычка из Руби :)

2020-06-05 08:59 UTC, the-action-man commented on part_04_testing/02/04_02.js
> +        if (item === "")
Сделано

2020-06-05 16:51 UTC, index01d approved these changes

2020-06-05 18:09 UTC, merged