Part 05 dom
the-action-man/tn-js pull request #3
Opened 2020-06-11 20:56 UTC by the-action-man

2020-06-13 08:17 UTC, index01d approved these changes

2020-06-13 08:17 UTC, index01d commented on part_05_DOM/01/01_01.js
> +// Реализовать 3 функции, выполняющие это разными способами
Вообще-то по заданию требовалось 3 способа :)

2020-06-13 08:20 UTC, index01d requested changes

2020-06-13 08:20 UTC, index01d commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> + * прошел ли регистрацию на рейс.
Не сумел найти список купленных билетов

2020-06-14 17:51 UTC, the-action-man commented on part_05_DOM/01/01_01.js
> +// Реализовать 3 функции, выполняющие это разными способами
Я не знаю какой тритий. Подскажите, пожалуйста.

2020-06-14 18:37 UTC, the-action-man commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> + * прошел ли регистрацию на рейс.
сделано

2020-06-14 19:19 UTC, index01d requested changes

2020-06-14 19:19 UTC, index01d commented on part_05_DOM/01/01_01.js
> +// Реализовать 3 функции, выполняющие это разными способами
Можно перебрать не только `children` или `childNodes` но и "братьев" с помощью `nextSibling`:
https://developer.mozilla.org/en-US/docs/Web/API/Node/nextSibling
https://learn.javascript.ru/traversing-dom

2020-06-14 22:16 UTC, the-action-man commented on part_05_DOM/01/01_01.js
> +// Реализовать 3 функции, выполняющие это разными способами
Спасибо!
Сделано.

2020-06-15 07:39 UTC, index01d approved these changes

2020-06-15 07:58 UTC, merged