Part 06 events
the-action-man/tn-js pull request #4
Opened 2020-06-17 21:04 UTC by the-action-man

2020-06-19 06:24 UTC, index01d requested changes
Ответ на вопрос: Так происходит, потому что при указании на месте стиль для элемента устанавливается сразу, а при указании в стилевом файле или теге style стиль применяется позже в процессе стадии "Attachment" (схема отрисовки страницы: https://miro.medium.com/max/624/1*srfAe9f1ryMc3qoMOASmhg.png). Получить вычисленное значение можно с помощью функции "window.getComputedStyle", но я не рекомендую применять её в случаях, когда можно этого не делать.

2020-06-19 06:26 UTC, index01d requested changes

2020-06-19 06:26 UTC, index01d commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +form.addEventListener('submit', submitHandlerOfTicketBuying);
`handleSubmit` или `handleTicketBuyingForm`

2020-06-27 11:20 UTC, the-action-man commented on part_03_deepening_into_js/flight-constrol-system/fcs.js
> +form.addEventListener('submit', submitHandlerOfTicketBuying);
Done
Thanks

2020-06-28 19:55 UTC, arswarog requested changes

2020-06-28 19:55 UTC, arswarog commented on part_03_deepening_into_js/flight-constrol-system/index.html
> +                    <input id="seatType" name="seatType" type="number" value="0" placeholder="Please enter your eat type">
Как и говорилось, можно сделать более удобным, например, выпадающим списком:

```html
                    <select id="seatType" name="seatType">
                        <option value="0" selected>Standard</option>
                        <option value="1">Business</option>
                    </select>
```

2020-06-28 19:55 UTC, arswarog commented on part_06_events/01/index.html
> +        const canvas = document.getElementsByTagName("table")[1];
Не стоит использовать доступ к элементу на всей странице но его номеру - если страницу потребуется изменить, и добавить еще таблицу, то придется это потом переписывать. Если обращаться по id то сколько бы новых таблиц не добавлялось - все будет работать как прежде
Стоит сразу писать такой код который минимально зависит от изменений окружающего кода

2020-06-29 13:34 UTC, the-action-man commented on part_06_events/01/index.html
> +        const canvas = document.getElementsByTagName("table")[1];
понял
благодарю

2020-06-30 07:38 UTC, arswarog approved these changes

2020-06-30 09:25 UTC, merged